// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4h7Ehv_KIsm4UKq_X0CbOvk3SHp8uZp4',
    appId: '1:1073593113343:web:d7e1020632952b3fd0caca',
    messagingSenderId: '1073593113343',
    projectId: 'closerrr-56695',
    authDomain: 'closerrr-56695.firebaseapp.com',
    storageBucket: 'closerrr-56695.firebasestorage.app',
    measurementId: 'G-WPCLS7P3JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUb7klbxPVCrDjp0auu5pHhkcgd3A03lU',
    appId: '1:1073593113343:android:b2ba9fe5fb5a0fc6d0caca',
    messagingSenderId: '1073593113343',
    projectId: 'closerrr-56695',
    storageBucket: 'closerrr-56695.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATV4OIwyUHUs_PyB0bH9qDuKF9W_0UXDg',
    appId: '1:1073593113343:ios:b43ebb65e17d7bd3d0caca',
    messagingSenderId: '1073593113343',
    projectId: 'closerrr-56695',
    storageBucket: 'closerrr-56695.firebasestorage.app',
    androidClientId: '1073593113343-iucfduh4rk27n5qgivcsslj51aj91493.apps.googleusercontent.com',
    iosClientId: '1073593113343-9vhsib1lh43pbc4rb6pbs9e17f57hvpm.apps.googleusercontent.com',
    iosBundleId: 'com.sharkbrewsinternational.closerrr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATV4OIwyUHUs_PyB0bH9qDuKF9W_0UXDg',
    appId: '1:1073593113343:ios:b43ebb65e17d7bd3d0caca',
    messagingSenderId: '1073593113343',
    projectId: 'closerrr-56695',
    storageBucket: 'closerrr-56695.firebasestorage.app',
    androidClientId: '1073593113343-iucfduh4rk27n5qgivcsslj51aj91493.apps.googleusercontent.com',
    iosClientId: '1073593113343-9vhsib1lh43pbc4rb6pbs9e17f57hvpm.apps.googleusercontent.com',
    iosBundleId: 'com.sharkbrewsinternational.closerrr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4h7Ehv_KIsm4UKq_X0CbOvk3SHp8uZp4',
    appId: '1:1073593113343:web:5ce68a5ceb749655d0caca',
    messagingSenderId: '1073593113343',
    projectId: 'closerrr-56695',
    authDomain: 'closerrr-56695.firebaseapp.com',
    storageBucket: 'closerrr-56695.firebasestorage.app',
    measurementId: 'G-P96XZQR7R9',
  );

}